
---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:

  roles:
    # Your code here
    - configure-Jenkins-server
    - configure-prometheus-node-exporter

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION:
      context:
      - AWSPolicy
      - Slack-notifications
    TYPEORM_ENTITIES:
      context:
      - AWSPolicy
      - Slack-notifications
    TYPEORM_HOST:
      context:
      - AWSPolicy
      - Slack-notifications
    TYPEORM_PORT:
      context:
      - AWSPolicy
      - Slack-notifications
    TYPEORM_USERNAME:
      context:
      - AWSPolicy
      - Slack-notifications
    TYPEORM_PASSWORD:
      context:
      - AWSPolicy
      - Slack-notifications
    TYPEORM_DATABASE:
      context:
      - AWSPolicy
      - Slack-notifications