---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes


- name: "Installation minikube"
  become: yes
  shell: |
         sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
         #sudo install minikube-linux-amd64 /usr/local/bin/minikube
  args:
     warn: false

- name: "Copy the downloaded file and store it into the /usr/local/bin/minikube directory"
  become: yes
  shell: |
          sudo cp minikube-linux-amd64 /usr/local/bin/minikube
  args:
     warn: false

- name: "give the file executive permission using"
  become: yes
  shell: |
          sudo chmod 755 /usr/local/bin/minikube
  args:
     warn: false

- name: "install minikube"
  become: yes
  shell: |
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
  args:
     warn: false

- name: "verify installed Minikube"
  become: yes
  shell: |
          minikube version
  args:
     warn: false