
AWSTemplateFormatVersion: 2010-09-09

Description: >
    Abdelrazek Rizk / Jenkins frontend stack.
    Project-5-Cloud-DevOps-Engineer-Capstone 

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  JenkinsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "jenkins-code-${ID}"
      AccessControl: PublicRead
  
  JenkinsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'JenkinsBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'JenkinsBucket', /*]]

Outputs:
  JenkinsBucket:
    Description: starter codebuild
    Value: !Ref 'JenkinsBucket'
